### PR TITLE
remove break so more than first route is matched to secret

### LINKED ISSUE #83: Multiple Routes with one secret fail to update
When two or more routes are annotated with the same secret only one is updated when the secret is updated unless you restart the operator.

### PR DESCRIPTION
**Pull request by mathianasj**
fixes #83

### CODE REVIEW

File: controllers/route/route_controller.go [hunk 1]
```diff
@@ -233,11 +233,9 @@ func (e *enqueueRequestForReferecingRoutes) matchSecret(c client.Client, secret
 	for _, route := range routeList.Items {
 		if secretName := route.GetAnnotations()[certAnnotation]; secretName == secret.Name && route.Spec.TLS != nil {
 			result = append(result, route)
-			break
```
Comment (raffaelespazzoli) [inline controllers/route/route_controller.go:236]: should this be a `continue`?, otherwise we risk returning a route twice.

Comment (mathianasj) [reply controllers/route/route_controller.go:236]: yes because they could be tagged with both annotations good catch, i'll make the change

**Comment by mathianasj** [comment]
@raffaelespazzoli let me know if this is good now, i retested as well
